package gin

import (
	"github.com/lwmacct/260101-go-pkg-ddd/pkg/modules/core/transport/gin/routes"
)

// crmRoutes 返回 CRM 域路由配置。
func (deps *RouterDependencies) crmRoutes() []routes.Route {
	// 基础中间件：认证 + RBAC
	baseMiddlewares := []routes.MiddlewareConfig{
		{Name: routes.MiddlewareRequestID},
		{Name: routes.MiddlewareOperationID},
		{Name: routes.MiddlewareAuth},
		{Name: routes.MiddlewareRBAC},
	}

	// 审计中间件：需要记录操作日志
	auditMiddlewares := append(cloneMiddlewares(baseMiddlewares),
		routes.MiddlewareConfig{Name: routes.MiddlewareAudit})

	return []routes.Route{
		// ==================== 联系人 CRUD ====================
		{
			Method:      routes.POST,
			Path:        "/api/crm/contacts",
			Handler:     deps.ContactHandler.Create,
			Op:          "crm:contacts:create",
			Middlewares: auditMiddlewares,
			Tags:        "CRM - Contacts",
			Summary:     "创建联系人",
			Description: "创建新联系人",
		},
		{
			Method:      routes.GET,
			Path:        "/api/crm/contacts",
			Handler:     deps.ContactHandler.List,
			Op:          "crm:contacts:list",
			Middlewares: baseMiddlewares,
			Tags:        "CRM - Contacts",
			Summary:     "联系人列表",
			Description: "分页获取联系人列表",
		},
		{
			Method:      routes.GET,
			Path:        "/api/crm/contacts/:id",
			Handler:     deps.ContactHandler.Get,
			Op:          "crm:contacts:get",
			Middlewares: baseMiddlewares,
			Tags:        "CRM - Contacts",
			Summary:     "联系人详情",
			Description: "获取联系人详细信息",
		},
		{
			Method:      routes.PUT,
			Path:        "/api/crm/contacts/:id",
			Handler:     deps.ContactHandler.Update,
			Op:          "crm:contacts:update",
			Middlewares: auditMiddlewares,
			Tags:        "CRM - Contacts",
			Summary:     "更新联系人",
			Description: "更新联系人信息",
		},
		{
			Method:      routes.DELETE,
			Path:        "/api/crm/contacts/:id",
			Handler:     deps.ContactHandler.Delete,
			Op:          "crm:contacts:delete",
			Middlewares: auditMiddlewares,
			Tags:        "CRM - Contacts",
			Summary:     "删除联系人",
			Description: "删除联系人",
		},

		// ==================== 公司 CRUD ====================
		{
			Method:      routes.POST,
			Path:        "/api/crm/companies",
			Handler:     deps.CompanyHandler.Create,
			Op:          "crm:companies:create",
			Middlewares: auditMiddlewares,
			Tags:        "CRM - Companies",
			Summary:     "创建公司",
			Description: "创建新公司",
		},
		{
			Method:      routes.GET,
			Path:        "/api/crm/companies",
			Handler:     deps.CompanyHandler.List,
			Op:          "crm:companies:list",
			Middlewares: baseMiddlewares,
			Tags:        "CRM - Companies",
			Summary:     "公司列表",
			Description: "分页获取公司列表",
		},
		{
			Method:      routes.GET,
			Path:        "/api/crm/companies/:id",
			Handler:     deps.CompanyHandler.Get,
			Op:          "crm:companies:get",
			Middlewares: baseMiddlewares,
			Tags:        "CRM - Companies",
			Summary:     "公司详情",
			Description: "获取公司详细信息",
		},
		{
			Method:      routes.PUT,
			Path:        "/api/crm/companies/:id",
			Handler:     deps.CompanyHandler.Update,
			Op:          "crm:companies:update",
			Middlewares: auditMiddlewares,
			Tags:        "CRM - Companies",
			Summary:     "更新公司",
			Description: "更新公司信息",
		},
		{
			Method:      routes.DELETE,
			Path:        "/api/crm/companies/:id",
			Handler:     deps.CompanyHandler.Delete,
			Op:          "crm:companies:delete",
			Middlewares: auditMiddlewares,
			Tags:        "CRM - Companies",
			Summary:     "删除公司",
			Description: "删除公司",
		},

		// ==================== 线索 CRUD ====================
		{
			Method:      routes.POST,
			Path:        "/api/crm/leads",
			Handler:     deps.LeadHandler.Create,
			Op:          "crm:leads:create",
			Middlewares: auditMiddlewares,
			Tags:        "CRM - Leads",
			Summary:     "创建线索",
			Description: "创建新线索",
		},
		{
			Method:      routes.GET,
			Path:        "/api/crm/leads",
			Handler:     deps.LeadHandler.List,
			Op:          "crm:leads:list",
			Middlewares: baseMiddlewares,
			Tags:        "CRM - Leads",
			Summary:     "线索列表",
			Description: "分页获取线索列表",
		},
		{
			Method:      routes.GET,
			Path:        "/api/crm/leads/:id",
			Handler:     deps.LeadHandler.Get,
			Op:          "crm:leads:get",
			Middlewares: baseMiddlewares,
			Tags:        "CRM - Leads",
			Summary:     "线索详情",
			Description: "获取线索详细信息",
		},
		{
			Method:      routes.PUT,
			Path:        "/api/crm/leads/:id",
			Handler:     deps.LeadHandler.Update,
			Op:          "crm:leads:update",
			Middlewares: auditMiddlewares,
			Tags:        "CRM - Leads",
			Summary:     "更新线索",
			Description: "更新线索信息",
		},
		{
			Method:      routes.DELETE,
			Path:        "/api/crm/leads/:id",
			Handler:     deps.LeadHandler.Delete,
			Op:          "crm:leads:delete",
			Middlewares: auditMiddlewares,
			Tags:        "CRM - Leads",
			Summary:     "删除线索",
			Description: "删除线索",
		},

		// ==================== 线索状态转换 ====================
		{
			Method:      routes.POST,
			Path:        "/api/crm/leads/:id/contact",
			Handler:     deps.LeadHandler.Contact,
			Op:          "crm:leads:contact",
			Middlewares: auditMiddlewares,
			Tags:        "CRM - Leads",
			Summary:     "标记为已联系",
			Description: "将线索状态转换为已联系（需要线索处于新建状态）",
		},
		{
			Method:      routes.POST,
			Path:        "/api/crm/leads/:id/qualify",
			Handler:     deps.LeadHandler.Qualify,
			Op:          "crm:leads:qualify",
			Middlewares: auditMiddlewares,
			Tags:        "CRM - Leads",
			Summary:     "标记为已确认",
			Description: "将线索状态转换为已确认（需要线索处于已联系状态）",
		},
		{
			Method:      routes.POST,
			Path:        "/api/crm/leads/:id/convert",
			Handler:     deps.LeadHandler.Convert,
			Op:          "crm:leads:convert",
			Middlewares: auditMiddlewares,
			Tags:        "CRM - Leads",
			Summary:     "转化为商机",
			Description: "将线索转化为商机（需要线索处于已确认状态）",
		},
		{
			Method:      routes.POST,
			Path:        "/api/crm/leads/:id/lose",
			Handler:     deps.LeadHandler.Lose,
			Op:          "crm:leads:lose",
			Middlewares: auditMiddlewares,
			Tags:        "CRM - Leads",
			Summary:     "标记为丢失",
			Description: "将线索标记为丢失（需要线索处于新建、已联系或已确认状态）",
		},

		// ==================== 商机 CRUD ====================
		{
			Method:      routes.POST,
			Path:        "/api/crm/opportunities",
			Handler:     deps.OpportunityHandler.Create,
			Op:          "crm:opportunities:create",
			Middlewares: auditMiddlewares,
			Tags:        "CRM - Opportunities",
			Summary:     "创建商机",
			Description: "创建新商机",
		},
		{
			Method:      routes.GET,
			Path:        "/api/crm/opportunities",
			Handler:     deps.OpportunityHandler.List,
			Op:          "crm:opportunities:list",
			Middlewares: baseMiddlewares,
			Tags:        "CRM - Opportunities",
			Summary:     "商机列表",
			Description: "分页获取商机列表",
		},
		{
			Method:      routes.GET,
			Path:        "/api/crm/opportunities/:id",
			Handler:     deps.OpportunityHandler.Get,
			Op:          "crm:opportunities:get",
			Middlewares: baseMiddlewares,
			Tags:        "CRM - Opportunities",
			Summary:     "商机详情",
			Description: "获取商机详细信息",
		},
		{
			Method:      routes.PUT,
			Path:        "/api/crm/opportunities/:id",
			Handler:     deps.OpportunityHandler.Update,
			Op:          "crm:opportunities:update",
			Middlewares: auditMiddlewares,
			Tags:        "CRM - Opportunities",
			Summary:     "更新商机",
			Description: "更新商机信息",
		},
		{
			Method:      routes.DELETE,
			Path:        "/api/crm/opportunities/:id",
			Handler:     deps.OpportunityHandler.Delete,
			Op:          "crm:opportunities:delete",
			Middlewares: auditMiddlewares,
			Tags:        "CRM - Opportunities",
			Summary:     "删除商机",
			Description: "删除商机",
		},

		// ==================== 商机阶段管理 ====================
		{
			Method:      routes.POST,
			Path:        "/api/crm/opportunities/:id/advance",
			Handler:     deps.OpportunityHandler.Advance,
			Op:          "crm:opportunities:advance",
			Middlewares: auditMiddlewares,
			Tags:        "CRM - Opportunities",
			Summary:     "推进商机阶段",
			Description: "将商机推进到下一阶段（prospecting → proposal → negotiation）",
		},
		{
			Method:      routes.POST,
			Path:        "/api/crm/opportunities/:id/close-won",
			Handler:     deps.OpportunityHandler.CloseWon,
			Op:          "crm:opportunities:close-won",
			Middlewares: auditMiddlewares,
			Tags:        "CRM - Opportunities",
			Summary:     "成交",
			Description: "将商机标记为成交（需要商机处于谈判阶段）",
		},
		{
			Method:      routes.POST,
			Path:        "/api/crm/opportunities/:id/close-lost",
			Handler:     deps.OpportunityHandler.CloseLost,
			Op:          "crm:opportunities:close-lost",
			Middlewares: auditMiddlewares,
			Tags:        "CRM - Opportunities",
			Summary:     "丢单",
			Description: "将商机标记为丢单（需要商机处于谈判阶段）",
		},
	}
}
