package routes

import (
	ginpermission "github.com/lwmacct/260101-go-pkg-ddd/pkg/adapters/http/permission"
	"github.com/lwmacct/260101-go-pkg-ddd/pkg/domain/permission"
)

// Registry 路由注册表（单一数据源）。
//
//nolint:gochecknoglobals // 注册表是只读全局配置
var Registry = map[permission.Operation]routeMeta{
	// ==================== Public 域（公开） ====================
	ginpermission.PublicAuthRegister: {
		Method:      POST,
		Path:        "/api/auth/register",
		Tags:        "Authentication",
		Audit:       true,
		Summary:     "注册",
		Description: "用户注册",
	},
	ginpermission.PublicAuthLogin: {
		Method:      POST,
		Path:        "/api/auth/login",
		Tags:        "Authentication",
		Audit:       true,
		Summary:     "登录",
		Description: "用户登录",
	},
	ginpermission.PublicAuthLogin2FA: {
		Method:      POST,
		Path:        "/api/auth/login/2fa",
		Tags:        "Authentication",
		Audit:       true,
		Summary:     "2FA 登录",
		Description: "两步验证登录",
	},
	ginpermission.PublicAuthRefresh: {
		Method:      POST,
		Path:        "/api/auth/refresh",
		Tags:        "Authentication",
		Audit:       true,
		Summary:     "刷新令牌",
		Description: "刷新访问令牌",
	},
	ginpermission.PublicAuthCaptcha: {
		Method:      GET,
		Path:        "/api/auth/captcha",
		Tags:        "Authentication",
		Summary:     "获取验证码",
		Description: "获取图形验证码",
	},

	// ==================== Self 域 - 2FA（需认证） ====================
	ginpermission.Self2FASetup: {
		Method:      POST,
		Path:        "/api/auth/2fa/setup",
		Tags:        "Authentication - 2FA",
		Audit:       true,
		Summary:     "设置 2FA",
		Description: "设置两步验证",
	},
	ginpermission.Self2FAVerify: {
		Method:      POST,
		Path:        "/api/auth/2fa/verify",
		Tags:        "Authentication - 2FA",
		Audit:       true,
		Summary:     "启用 2FA",
		Description: "验证并启用两步验证",
	},
	ginpermission.Self2FADisable: {
		Method:      POST,
		Path:        "/api/auth/2fa/disable",
		Tags:        "Authentication - 2FA",
		Audit:       true,
		Summary:     "禁用 2FA",
		Description: "禁用两步验证",
	},
	ginpermission.Self2FAStatus: {
		Method:      GET,
		Path:        "/api/auth/2fa/status",
		Tags:        "Authentication - 2FA",
		Summary:     "2FA 状态",
		Description: "获取两步验证状态",
	},

	// ==================== Sys 域 - 用户管理 ====================
	ginpermission.AdminUsersCreate: {
		Method:      POST,
		Path:        "/api/admin/users",
		Tags:        "Admin - User Management",
		Audit:       true,
		Summary:     "创建用户",
		Description: "创建新用户",
	},
	ginpermission.AdminUsersBatchCreate: {
		Method:      POST,
		Path:        "/api/admin/users/batch",
		Tags:        "Admin - User Management",
		Audit:       true,
		Summary:     "批量创建用户",
		Description: "批量创建用户",
	},
	ginpermission.AdminUsersList: {
		Method:      GET,
		Path:        "/api/admin/users",
		Tags:        "Admin - User Management",
		Summary:     "用户列表",
		Description: "获取用户列表",
	},
	ginpermission.AdminUsersGet: {
		Method:      GET,
		Path:        "/api/admin/users/:id",
		Tags:        "Admin - User Management",
		Summary:     "用户详情",
		Description: "获取用户详情",
	},
	ginpermission.AdminUsersUpdate: {
		Method:      PUT,
		Path:        "/api/admin/users/:id",
		Tags:        "Admin - User Management",
		Audit:       true,
		Summary:     "更新用户",
		Description: "更新用户信息",
	},
	ginpermission.AdminUsersDelete: {
		Method:      DELETE,
		Path:        "/api/admin/users/:id",
		Tags:        "Admin - User Management",
		Audit:       true,
		Summary:     "删除用户",
		Description: "删除用户",
	},
	ginpermission.AdminUsersAssignRoles: {
		Method:      PUT,
		Path:        "/api/admin/users/:id/roles",
		Tags:        "Admin - User Management",
		Audit:       true,
		Summary:     "分配角色",
		Description: "为用户分配角色",
	},

	// ==================== Sys 域 - 角色管理 ====================
	ginpermission.AdminRolesCreate: {
		Method:      POST,
		Path:        "/api/admin/roles",
		Tags:        "Admin - Role Management",
		Audit:       true,
		Summary:     "创建角色",
		Description: "创建角色",
	},
	ginpermission.AdminRolesList: {
		Method:      GET,
		Path:        "/api/admin/roles",
		Tags:        "Admin - Role Management",
		Summary:     "角色列表",
		Description: "获取角色列表",
	},
	ginpermission.AdminRolesGet: {
		Method:      GET,
		Path:        "/api/admin/roles/:id",
		Tags:        "Admin - Role Management",
		Summary:     "角色详情",
		Description: "获取角色详情",
	},
	ginpermission.AdminRolesUpdate: {
		Method:      PUT,
		Path:        "/api/admin/roles/:id",
		Tags:        "Admin - Role Management",
		Audit:       true,
		Summary:     "更新角色",
		Description: "更新角色",
	},
	ginpermission.AdminRolesDelete: {
		Method:      DELETE,
		Path:        "/api/admin/roles/:id",
		Tags:        "Admin - Role Management",
		Audit:       true,
		Summary:     "删除角色",
		Description: "删除角色",
	},
	ginpermission.AdminRolesSetPermissions: {
		Method:      PUT,
		Path:        "/api/admin/roles/:id/permissions",
		Tags:        "Admin - Role Management",
		Audit:       true,
		Summary:     "设置权限",
		Description: "设置角色权限",
	},

	// ==================== Sys 域 - 操作列表 ====================
	ginpermission.AdminOperationsList: {
		Method:      GET,
		Path:        "/api/admin/operations",
		Tags:        "System",
		Summary:     "操作列表",
		Description: "获取可用操作列表",
	},

	// ==================== Sys 域 - 审计日志 ====================
	ginpermission.AdminAuditList: {
		Method:      GET,
		Path:        "/api/admin/audit",
		Tags:        "Admin - Audit Log",
		Summary:     "审计日志列表",
		Description: "获取审计日志列表",
	},
	ginpermission.AdminAuditGet: {
		Method:      GET,
		Path:        "/api/admin/audit/:id",
		Tags:        "Admin - Audit Log",
		Summary:     "审计日志详情",
		Description: "获取审计日志详情",
	},
	ginpermission.AdminAuditActions: {
		Method:      GET,
		Path:        "/api/admin/audit/actions",
		Tags:        "Admin - Audit Log",
		Summary:     "审计操作定义",
		Description: "获取审计操作定义",
	},

	// ==================== Sys 域 - 系统概览 ====================
	ginpermission.AdminOverviewStats: {
		Method:      GET,
		Path:        "/api/admin/overview/stats",
		Tags:        "Overview",
		Summary:     "系统概览",
		Description: "获取系统概览统计",
	},

	// ==================== Sys 域 - 系统配置 ====================
	ginpermission.AdminSettingsCreate: {
		Method:      POST,
		Path:        "/api/admin/settings",
		Tags:        "Admin - Settings",
		Audit:       true,
		Summary:     "创建配置",
		Description: "创建配置项",
	},
	ginpermission.AdminSettingsList: {
		Method:      GET,
		Path:        "/api/admin/settings",
		Tags:        "Admin - Settings",
		Summary:     "配置列表",
		Description: "获取配置列表",
	},
	ginpermission.AdminSettingsGet: {
		Method:      GET,
		Path:        "/api/admin/settings/:key",
		Tags:        "Admin - Settings",
		Summary:     "配置详情",
		Description: "获取配置详情",
	},
	ginpermission.AdminSettingsUpdate: {
		Method:      PUT,
		Path:        "/api/admin/settings/:key",
		Tags:        "Admin - Settings",
		Audit:       true,
		Summary:     "更新配置",
		Description: "更新配置",
	},
	ginpermission.AdminSettingsDelete: {
		Method:      DELETE,
		Path:        "/api/admin/settings/:key",
		Tags:        "Admin - Settings",
		Audit:       true,
		Summary:     "删除配置",
		Description: "删除配置",
	},
	ginpermission.AdminSettingsBatchUpdate: {
		Method:      POST,
		Path:        "/api/admin/settings/batch",
		Tags:        "Admin - Settings",
		Audit:       true,
		Summary:     "批量更新配置",
		Description: "批量更新配置",
	},

	// ==================== Sys 域 - 配置分类 ====================
	ginpermission.AdminSettingCategoriesList: {
		Method:      GET,
		Path:        "/api/admin/settings/categories",
		Tags:        "Admin - Setting Categories",
		Summary:     "配置分类列表",
		Description: "获取配置分类列表",
	},
	ginpermission.AdminSettingCategoriesGet: {
		Method:      GET,
		Path:        "/api/admin/settings/categories/:id",
		Tags:        "Admin - Setting Categories",
		Summary:     "配置分类详情",
		Description: "获取配置分类详情",
	},
	ginpermission.AdminSettingCategoriesCreate: {
		Method:      POST,
		Path:        "/api/admin/settings/categories",
		Tags:        "Admin - Setting Categories",
		Audit:       true,
		Summary:     "创建配置分类",
		Description: "创建配置分类",
	},
	ginpermission.AdminSettingCategoriesUpdate: {
		Method:      PUT,
		Path:        "/api/admin/settings/categories/:id",
		Tags:        "Admin - Setting Categories",
		Audit:       true,
		Summary:     "更新配置分类",
		Description: "更新配置分类",
	},
	ginpermission.AdminSettingCategoriesDelete: {
		Method:      DELETE,
		Path:        "/api/admin/settings/categories/:id",
		Tags:        "Admin - Setting Categories",
		Audit:       true,
		Summary:     "删除配置分类",
		Description: "删除配置分类",
	},

	// ==================== Sys 域 - 缓存管理 ====================
	ginpermission.AdminCacheInfo: {
		Method:      GET,
		Path:        "/api/admin/cache/info",
		Tags:        "System",
		Summary:     "缓存信息",
		Description: "获取缓存信息",
	},
	ginpermission.AdminCacheScanKeys: {
		Method:      GET,
		Path:        "/api/admin/cache/keys",
		Tags:        "System",
		Summary:     "扫描缓存键",
		Description: "扫描缓存键",
	},
	ginpermission.AdminCacheGetKey: {
		Method:      GET,
		Path:        "/api/admin/cache/key",
		Tags:        "System",
		Summary:     "获取缓存值",
		Description: "获取缓存键值",
	},
	ginpermission.AdminCacheDeleteKey: {
		Method:      DELETE,
		Path:        "/api/admin/cache/key",
		Tags:        "System",
		Audit:       true,
		Summary:     "删除缓存键",
		Description: "删除缓存键",
	},
	ginpermission.AdminCacheDeletePattern: {
		Method:      DELETE,
		Path:        "/api/admin/cache/keys",
		Tags:        "System",
		Audit:       true,
		Summary:     "批量删除缓存",
		Description: "按模式删除缓存键",
	},

	// ==================== Self 域 - 个人资料 ====================
	ginpermission.SelfProfileGet: {
		Method:      GET,
		Path:        "/api/user/profile",
		Tags:        "User - Profile",
		Summary:     "获取资料",
		Description: "获取当前用户资料",
	},
	ginpermission.SelfProfileUpdate: {
		Method:      PUT,
		Path:        "/api/user/profile",
		Tags:        "User - Profile",
		Audit:       true,
		Summary:     "更新资料",
		Description: "更新当前用户资料",
	},
	ginpermission.SelfPasswordUpdate: {
		Method:      PUT,
		Path:        "/api/user/password",
		Tags:        "User - Profile",
		Audit:       true,
		Summary:     "修改密码",
		Description: "修改密码",
	},
	ginpermission.SelfAccountDelete: {
		Method:      DELETE,
		Path:        "/api/user/account",
		Tags:        "User - Profile",
		Audit:       true,
		Summary:     "注销账户",
		Description: "删除账户",
	},

	// ==================== Self 域 - 访问令牌 ====================
	ginpermission.SelfTokensCreate: {
		Method:      POST,
		Path:        "/api/user/tokens",
		Tags:        "User - Personal Access Token",
		Audit:       true,
		Summary:     "创建令牌",
		Description: "创建访问令牌",
	},
	ginpermission.SelfTokensList: {
		Method:      GET,
		Path:        "/api/user/tokens",
		Tags:        "User - Personal Access Token",
		Summary:     "令牌列表",
		Description: "获取访问令牌列表",
	},
	ginpermission.SelfTokensGet: {
		Method:      GET,
		Path:        "/api/user/tokens/:id",
		Tags:        "User - Personal Access Token",
		Summary:     "令牌详情",
		Description: "获取令牌详情",
	},
	ginpermission.SelfTokensDelete: {
		Method:      DELETE,
		Path:        "/api/user/tokens/:id",
		Tags:        "User - Personal Access Token",
		Audit:       true,
		Summary:     "删除令牌",
		Description: "删除令牌",
	},
	ginpermission.SelfTokensDisable: {
		Method:      PATCH,
		Path:        "/api/user/tokens/:id/disable",
		Tags:        "User - Personal Access Token",
		Audit:       true,
		Summary:     "禁用令牌",
		Description: "禁用令牌",
	},
	ginpermission.SelfTokensEnable: {
		Method:      PATCH,
		Path:        "/api/user/tokens/:id/enable",
		Tags:        "User - Personal Access Token",
		Audit:       true,
		Summary:     "启用令牌",
		Description: "启用令牌",
	},
	ginpermission.SelfTokensScopes: {
		Method:      GET,
		Path:        "/api/user/tokens/scopes",
		Tags:        "User - Personal Access Token",
		Summary:     "Scope 列表",
		Description: "获取创建 PAT 时可选的权限范围列表",
	},

	// ==================== Self 域 - 用户配置 ====================
	ginpermission.SelfSettingsCategoriesList: {
		Method:      GET,
		Path:        "/api/user/settings/categories",
		Tags:        "User - Settings",
		Summary:     "配置分类列表",
		Description: "获取用户配置分类",
	},
	ginpermission.SelfSettingsList: {
		Method:      GET,
		Path:        "/api/user/settings",
		Tags:        "User - Settings",
		Summary:     "用户配置列表",
		Description: "获取所有用户配置",
	},
	ginpermission.SelfSettingsGet: {
		Method:      GET,
		Path:        "/api/user/settings/:key",
		Tags:        "User - Settings",
		Summary:     "用户配置详情",
		Description: "获取用户配置项",
	},
	ginpermission.SelfSettingsSet: {
		Method:      PUT,
		Path:        "/api/user/settings/:key",
		Tags:        "User - Settings",
		Audit:       true,
		Summary:     "设置用户配置",
		Description: "设置用户配置",
	},
	ginpermission.SelfSettingsReset: {
		Method:      DELETE,
		Path:        "/api/user/settings/:key",
		Tags:        "User - Settings",
		Audit:       true,
		Summary:     "重置用户配置",
		Description: "重置用户配置",
	},
	ginpermission.SelfSettingsBatchSet: {
		Method:      POST,
		Path:        "/api/user/settings/batch",
		Tags:        "User - Settings",
		Audit:       true,
		Summary:     "批量设置配置",
		Description: "批量设置用户配置",
	},

	// ==================== Self 域 - 用户组织/团队 ====================
	ginpermission.SelfOrgsList: {
		Method:      GET,
		Path:        "/api/user/orgs",
		Tags:        "User - Organization",
		Summary:     "我的组织",
		Description: "获取当前用户加入的所有组织",
	},
	ginpermission.SelfTeamsList: {
		Method:      GET,
		Path:        "/api/user/teams",
		Tags:        "User - Organization",
		Summary:     "我的团队",
		Description: "获取当前用户加入的所有团队",
	},

	// ==================== Admin 域 - 组织管理 ====================
	ginpermission.AdminOrgsCreate: {
		Method:      POST,
		Path:        "/api/admin/orgs",
		Tags:        "Admin - Organization Management",
		Audit:       true,
		Summary:     "创建组织",
		Description: "系统管理员创建新组织",
	},
	ginpermission.AdminOrgsList: {
		Method:      GET,
		Path:        "/api/admin/orgs",
		Tags:        "Admin - Organization Management",
		Summary:     "组织列表",
		Description: "分页获取所有组织",
	},
	ginpermission.AdminOrgsGet: {
		Method:      GET,
		Path:        "/api/admin/orgs/:id",
		Tags:        "Admin - Organization Management",
		Summary:     "组织详情",
		Description: "根据 ID 获取组织详情",
	},
	ginpermission.AdminOrgsUpdate: {
		Method:      PUT,
		Path:        "/api/admin/orgs/:id",
		Tags:        "Admin - Organization Management",
		Audit:       true,
		Summary:     "更新组织",
		Description: "更新组织信息",
	},
	ginpermission.AdminOrgsDelete: {
		Method:      DELETE,
		Path:        "/api/admin/orgs/:id",
		Tags:        "Admin - Organization Management",
		Audit:       true,
		Summary:     "删除组织",
		Description: "软删除组织",
	},

	// ==================== Org 域 - 组织成员管理 ====================
	ginpermission.OrgMembersList: {
		Method:      GET,
		Path:        "/api/org/:org_id/members",
		Tags:        "Organization - Member Management",
		Summary:     "成员列表",
		Description: "分页获取组织成员列表",
	},
	ginpermission.OrgMembersAdd: {
		Method:      POST,
		Path:        "/api/org/:org_id/members",
		Tags:        "Organization - Member Management",
		Audit:       true,
		Summary:     "添加成员",
		Description: "添加用户到组织",
	},
	ginpermission.OrgMembersRemove: {
		Method:      DELETE,
		Path:        "/api/org/:org_id/members/:user_id",
		Tags:        "Organization - Member Management",
		Audit:       true,
		Summary:     "移除成员",
		Description: "从组织中移除成员",
	},
	ginpermission.OrgMembersUpdateRole: {
		Method:      PUT,
		Path:        "/api/org/:org_id/members/:user_id/role",
		Tags:        "Organization - Member Management",
		Audit:       true,
		Summary:     "更新成员角色",
		Description: "更新组织成员的角色",
	},

	// ==================== Org 域 - 团队管理 ====================
	ginpermission.OrgTeamsCreate: {
		Method:      POST,
		Path:        "/api/org/:org_id/teams",
		Tags:        "Organization - Team Management",
		Audit:       true,
		Summary:     "创建团队",
		Description: "在组织内创建新团队",
	},
	ginpermission.OrgTeamsList: {
		Method:      GET,
		Path:        "/api/org/:org_id/teams",
		ReadOnly:    true,
		Tags:        "Organization - Team Management",
		Summary:     "团队列表",
		Description: "分页获取组织内的团队列表",
	},
	ginpermission.OrgTeamsGet: {
		Method:      GET,
		Path:        "/api/org/:org_id/teams/:team_id",
		ReadOnly:    true,
		Tags:        "Organization - Team Management",
		Summary:     "团队详情",
		Description: "获取团队详情",
	},
	ginpermission.OrgTeamsUpdate: {
		Method:      PUT,
		Path:        "/api/org/:org_id/teams/:team_id",
		Tags:        "Organization - Team Management",
		Audit:       true,
		Summary:     "更新团队",
		Description: "更新团队信息",
	},
	ginpermission.OrgTeamsDelete: {
		Method:      DELETE,
		Path:        "/api/org/:org_id/teams/:team_id",
		Tags:        "Organization - Team Management",
		Audit:       true,
		Summary:     "删除团队",
		Description: "软删除团队",
	},

	// ==================== Org 域 - 团队成员管理 ====================
	ginpermission.OrgTeamMembersList: {
		Method:      GET,
		Path:        "/api/org/:org_id/teams/:team_id/members",
		ReadOnly:    true,
		Tags:        "Organization - Team Member Management",
		Summary:     "团队成员列表",
		Description: "分页获取团队成员列表",
	},
	ginpermission.OrgTeamMembersAdd: {
		Method:      POST,
		Path:        "/api/org/:org_id/teams/:team_id/members",
		Tags:        "Organization - Team Member Management",
		Audit:       true,
		Summary:     "添加团队成员",
		Description: "添加用户到团队（用户必须先是组织成员）",
	},
	ginpermission.OrgTeamMembersRemove: {
		Method:      DELETE,
		Path:        "/api/org/:org_id/teams/:team_id/members/:user_id",
		Tags:        "Organization - Team Member Management",
		Audit:       true,
		Summary:     "移除团队成员",
		Description: "从团队中移除成员",
	},

	// ==================== Sys 域 - 产品管理 ====================
	ginpermission.AdminProductsCreate: {
		Method:      POST,
		Path:        "/api/admin/products",
		Tags:        "Admin - Product Management",
		Audit:       true,
		Summary:     "创建产品",
		Description: "创建可订阅的产品",
	},
	ginpermission.AdminProductsList: {
		Method:      GET,
		Path:        "/api/admin/products",
		Tags:        "Admin - Product Management",
		Summary:     "产品列表",
		Description: "分页获取产品列表",
	},
	ginpermission.AdminProductsGet: {
		Method:      GET,
		Path:        "/api/admin/products/:id",
		Tags:        "Admin - Product Management",
		Summary:     "产品详情",
		Description: "获取产品详细信息",
	},
	ginpermission.AdminProductsUpdate: {
		Method:      PUT,
		Path:        "/api/admin/products/:id",
		Tags:        "Admin - Product Management",
		Audit:       true,
		Summary:     "更新产品",
		Description: "更新产品信息",
	},
	ginpermission.AdminProductsDelete: {
		Method:      DELETE,
		Path:        "/api/admin/products/:id",
		Tags:        "Admin - Product Management",
		Audit:       true,
		Summary:     "删除产品",
		Description: "删除产品（软删除）",
	},

	// ==================== Org 域 - 团队任务管理 ====================
	ginpermission.OrgTasksCreate: {
		Method:      POST,
		Path:        "/api/org/:org_id/teams/:team_id/tasks",
		Tags:        "Organization - Task Management",
		Audit:       true,
		Summary:     "创建任务",
		Description: "在团队内创建新任务",
	},
	ginpermission.OrgTasksList: {
		Method:      GET,
		Path:        "/api/org/:org_id/teams/:team_id/tasks",
		ReadOnly:    true,
		Tags:        "Organization - Task Management",
		Summary:     "任务列表",
		Description: "分页获取团队任务列表",
	},
	ginpermission.OrgTasksGet: {
		Method:      GET,
		Path:        "/api/org/:org_id/teams/:team_id/tasks/:id",
		ReadOnly:    true,
		Tags:        "Organization - Task Management",
		Summary:     "任务详情",
		Description: "获取任务详细信息",
	},
	ginpermission.OrgTasksUpdate: {
		Method:      PUT,
		Path:        "/api/org/:org_id/teams/:team_id/tasks/:id",
		Tags:        "Organization - Task Management",
		Audit:       true,
		Summary:     "更新任务",
		Description: "更新任务信息",
	},
	ginpermission.OrgTasksDelete: {
		Method:      DELETE,
		Path:        "/api/org/:org_id/teams/:team_id/tasks/:id",
		Tags:        "Organization - Task Management",
		Audit:       true,
		Summary:     "删除任务",
		Description: "删除任务",
	},
}
