package http

import (
	"github.com/lwmacct/260101-go-pkg-ddd/pkg/adapters/http/permission"
	"github.com/lwmacct/260101-go-pkg-ddd/pkg/adapters/http/routes"
)

// adminRoutes 返回 Admin 域所有路由
//
//nolint:maintidx // 路由定义是声明式配置，复杂度指标不适用
func (deps *RouterDependencies) adminRoutes() []routes.Route {
	// Admin 域中间件模式
	baseMiddlewares := []routes.MiddlewareConfig{
		{Name: routes.MiddlewareRequestID},
		{Name: routes.MiddlewareOperationID},
		{Name: routes.MiddlewareAuth},
		{Name: routes.MiddlewareRBAC},
	}
	auditMiddlewares := append(cloneMiddlewares(baseMiddlewares), routes.MiddlewareConfig{Name: routes.MiddlewareAudit})

	return []routes.Route{
		// ==================== 用户管理 ====================
		{
			Method:      routes.POST,
			Path:        "/api/admin/users",
			Handler:     deps.AdminUserHandler.CreateUser,
			Op:          permission.AdminUsersCreate,
			Middlewares: auditMiddlewares,
			Tags:        "Admin - User Management",
			Summary:     "创建用户",
			Description: "创建新用户",
		},
		{
			Method:      routes.POST,
			Path:        "/api/admin/users/batch",
			Handler:     deps.AdminUserHandler.BatchCreateUsers,
			Op:          permission.AdminUsersBatchCreate,
			Middlewares: auditMiddlewares,
			Tags:        "Admin - User Management",
			Summary:     "批量创建用户",
			Description: "批量创建用户",
		},
		{
			Method:      routes.GET,
			Path:        "/api/admin/users",
			Handler:     deps.AdminUserHandler.ListUsers,
			Op:          permission.AdminUsersList,
			Middlewares: baseMiddlewares,
			Tags:        "Admin - User Management",
			Summary:     "用户列表",
			Description: "获取用户列表",
		},
		{
			Method:      routes.GET,
			Path:        "/api/admin/users/:id",
			Handler:     deps.AdminUserHandler.GetUser,
			Op:          permission.AdminUsersGet,
			Middlewares: baseMiddlewares,
			Tags:        "Admin - User Management",
			Summary:     "获取用户",
			Description: "获取用户详情",
		},
		{
			Method:      routes.PUT,
			Path:        "/api/admin/users/:id",
			Handler:     deps.AdminUserHandler.UpdateUser,
			Op:          permission.AdminUsersUpdate,
			Middlewares: auditMiddlewares,
			Tags:        "Admin - User Management",
			Summary:     "更新用户",
			Description: "更新用户信息",
		},
		{
			Method:      routes.DELETE,
			Path:        "/api/admin/users/:id",
			Handler:     deps.AdminUserHandler.DeleteUser,
			Op:          permission.AdminUsersDelete,
			Middlewares: auditMiddlewares,
			Tags:        "Admin - User Management",
			Summary:     "删除用户",
			Description: "删除用户",
		},
		{
			Method:      routes.PUT,
			Path:        "/api/admin/users/:id/roles",
			Handler:     deps.AdminUserHandler.AssignRoles,
			Op:          permission.AdminUsersAssignRoles,
			Middlewares: auditMiddlewares,
			Tags:        "Admin - User Management",
			Summary:     "分配角色",
			Description: "为用户分配角色",
		},

		// ==================== 角色管理 ====================
		{
			Method:      routes.POST,
			Path:        "/api/admin/roles",
			Handler:     deps.RoleHandler.CreateRole,
			Op:          permission.AdminRolesCreate,
			Middlewares: auditMiddlewares,
			Tags:        "Admin - Role Management",
			Summary:     "创建角色",
			Description: "创建角色",
		},
		{
			Method:      routes.GET,
			Path:        "/api/admin/roles",
			Handler:     deps.RoleHandler.ListRoles,
			Op:          permission.AdminRolesList,
			Middlewares: baseMiddlewares,
			Tags:        "Admin - Role Management",
			Summary:     "角色列表",
			Description: "获取角色列表",
		},
		{
			Method:      routes.GET,
			Path:        "/api/admin/roles/:id",
			Handler:     deps.RoleHandler.GetRole,
			Op:          permission.AdminRolesGet,
			Middlewares: baseMiddlewares,
			Tags:        "Admin - Role Management",
			Summary:     "获取角色",
			Description: "获取角色详情",
		},
		{
			Method:      routes.PUT,
			Path:        "/api/admin/roles/:id",
			Handler:     deps.RoleHandler.UpdateRole,
			Op:          permission.AdminRolesUpdate,
			Middlewares: auditMiddlewares,
			Tags:        "Admin - Role Management",
			Summary:     "更新角色",
			Description: "更新角色信息",
		},
		{
			Method:      routes.DELETE,
			Path:        "/api/admin/roles/:id",
			Handler:     deps.RoleHandler.DeleteRole,
			Op:          permission.AdminRolesDelete,
			Middlewares: auditMiddlewares,
			Tags:        "Admin - Role Management",
			Summary:     "删除角色",
			Description: "删除角色",
		},
		{
			Method:      routes.PUT,
			Path:        "/api/admin/roles/:id/permissions",
			Handler:     deps.RoleHandler.SetPermissions,
			Op:          permission.AdminRolesSetPermissions,
			Middlewares: auditMiddlewares,
			Tags:        "Admin - Role Management",
			Summary:     "设置权限",
			Description: "设置角色权限",
		},

		// ==================== 组织管理 ====================
		{
			Method:      routes.POST,
			Path:        "/api/admin/orgs",
			Handler:     deps.OrgHandler.Create,
			Op:          permission.AdminOrgsCreate,
			Middlewares: auditMiddlewares,
			Tags:        "Admin - Organizations",
			Summary:     "创建组织",
			Description: "创建组织",
		},
		{
			Method:      routes.GET,
			Path:        "/api/admin/orgs",
			Handler:     deps.OrgHandler.List,
			Op:          permission.AdminOrgsList,
			Middlewares: baseMiddlewares,
			Tags:        "Admin - Organizations",
			Summary:     "组织列表",
			Description: "获取组织列表",
		},
		{
			Method:      routes.GET,
			Path:        "/api/admin/orgs/:id",
			Handler:     deps.OrgHandler.Get,
			Op:          permission.AdminOrgsGet,
			Middlewares: baseMiddlewares,
			Tags:        "Admin - Organizations",
			Summary:     "组织详情",
			Description: "获取组织详情",
		},
		{
			Method:      routes.PUT,
			Path:        "/api/admin/orgs/:id",
			Handler:     deps.OrgHandler.Update,
			Op:          permission.AdminOrgsUpdate,
			Middlewares: auditMiddlewares,
			Tags:        "Admin - Organizations",
			Summary:     "更新组织",
			Description: "更新组织信息",
		},
		{
			Method:      routes.DELETE,
			Path:        "/api/admin/orgs/:id",
			Handler:     deps.OrgHandler.Delete,
			Op:          permission.AdminOrgsDelete,
			Middlewares: auditMiddlewares,
			Tags:        "Admin - Organizations",
			Summary:     "删除组织",
			Description: "删除组织",
		},

		// ==================== 操作列表 ====================
		{
			Method:      routes.GET,
			Path:        "/api/admin/operations",
			Handler:     deps.OperationHandler.ListOperations,
			Op:          permission.AdminOperationsList,
			Middlewares: baseMiddlewares,
			Tags:        "Admin - System",
			Summary:     "操作列表",
			Description: "获取所有操作",
		},

		// ==================== 审计日志 ====================
		{
			Method:      routes.GET,
			Path:        "/api/admin/audit/actions",
			Handler:     deps.AuditHandler.GetActions,
			Op:          permission.AdminAuditActions,
			Middlewares: baseMiddlewares,
			Tags:        "Admin - Audit",
			Summary:     "审计操作",
			Description: "获取审计操作列表",
		},
		{
			Method:      routes.GET,
			Path:        "/api/admin/audit",
			Handler:     deps.AuditHandler.ListLogs,
			Op:          permission.AdminAuditList,
			Middlewares: baseMiddlewares,
			Tags:        "Admin - Audit",
			Summary:     "审计日志",
			Description: "获取审计日志列表",
		},
		{
			Method:      routes.GET,
			Path:        "/api/admin/audit/:id",
			Handler:     deps.AuditHandler.GetLog,
			Op:          permission.AdminAuditGet,
			Middlewares: baseMiddlewares,
			Tags:        "Admin - Audit",
			Summary:     "审计日志详情",
			Description: "获取审计日志详情",
		},

		// ==================== 系统概览 ====================
		{
			Method:      routes.GET,
			Path:        "/api/admin/overview/stats",
			Handler:     deps.OverviewHandler.GetStats,
			Op:          permission.AdminOverviewStats,
			Middlewares: baseMiddlewares,
			Tags:        "Admin - Overview",
			Summary:     "系统概览",
			Description: "获取系统概览数据",
		},

		// ==================== 配置分类 ====================
		{
			Method:      routes.GET,
			Path:        "/api/admin/settings/categories",
			Handler:     deps.SettingHandler.GetCategories,
			Op:          permission.AdminSettingCategoriesList,
			Middlewares: baseMiddlewares,
			Tags:        "Admin - Settings",
			Summary:     "配置分类列表",
			Description: "获取配置分类列表",
		},
		{
			Method:      routes.GET,
			Path:        "/api/admin/settings/categories/:key",
			Handler:     deps.SettingHandler.GetCategory,
			Op:          permission.AdminSettingCategoriesGet,
			Middlewares: baseMiddlewares,
			Tags:        "Admin - Settings",
			Summary:     "配置分类详情",
			Description: "获取配置分类详情",
		},
		{
			Method:      routes.POST,
			Path:        "/api/admin/settings/categories",
			Handler:     deps.SettingHandler.CreateCategory,
			Op:          permission.AdminSettingCategoriesCreate,
			Middlewares: auditMiddlewares,
			Tags:        "Admin - Settings",
			Summary:     "创建配置分类",
			Description: "创建配置分类",
		},
		{
			Method:      routes.PUT,
			Path:        "/api/admin/settings/categories/:key",
			Handler:     deps.SettingHandler.UpdateCategory,
			Op:          permission.AdminSettingCategoriesUpdate,
			Middlewares: auditMiddlewares,
			Tags:        "Admin - Settings",
			Summary:     "更新配置分类",
			Description: "更新配置分类",
		},
		{
			Method:      routes.DELETE,
			Path:        "/api/admin/settings/categories/:key",
			Handler:     deps.SettingHandler.DeleteCategory,
			Op:          permission.AdminSettingCategoriesDelete,
			Middlewares: auditMiddlewares,
			Tags:        "Admin - Settings",
			Summary:     "删除配置分类",
			Description: "删除配置分类",
		},

		// ==================== 系统配置 ====================
		{
			Method:      routes.POST,
			Path:        "/api/admin/settings/batch",
			Handler:     deps.SettingHandler.BatchUpdateSettings,
			Op:          permission.AdminSettingsBatchUpdate,
			Middlewares: auditMiddlewares,
			Tags:        "Admin - Settings",
			Summary:     "批量更新配置",
			Description: "批量更新系统配置",
		},
		{
			Method:      routes.POST,
			Path:        "/api/admin/settings",
			Handler:     deps.SettingHandler.CreateSetting,
			Op:          permission.AdminSettingsCreate,
			Middlewares: auditMiddlewares,
			Tags:        "Admin - Settings",
			Summary:     "创建配置",
			Description: "创建系统配置",
		},
		{
			Method:      routes.GET,
			Path:        "/api/admin/settings",
			Handler:     deps.SettingHandler.GetSettings,
			Op:          permission.AdminSettingsList,
			Middlewares: baseMiddlewares,
			Tags:        "Admin - Settings",
			Summary:     "配置列表",
			Description: "获取系统配置列表",
		},
		{
			Method:      routes.GET,
			Path:        "/api/admin/settings/:key",
			Handler:     deps.SettingHandler.GetSetting,
			Op:          permission.AdminSettingsGet,
			Middlewares: baseMiddlewares,
			Tags:        "Admin - Settings",
			Summary:     "配置详情",
			Description: "获取系统配置详情",
		},
		{
			Method:      routes.PUT,
			Path:        "/api/admin/settings/:key",
			Handler:     deps.SettingHandler.UpdateSetting,
			Op:          permission.AdminSettingsUpdate,
			Middlewares: auditMiddlewares,
			Tags:        "Admin - Settings",
			Summary:     "更新配置",
			Description: "更新系统配置",
		},
		{
			Method:      routes.DELETE,
			Path:        "/api/admin/settings/:key",
			Handler:     deps.SettingHandler.DeleteSetting,
			Op:          permission.AdminSettingsDelete,
			Middlewares: auditMiddlewares,
			Tags:        "Admin - Settings",
			Summary:     "删除配置",
			Description: "删除系统配置",
		},

		// ==================== 缓存管理 ====================
		{
			Method:      routes.GET,
			Path:        "/api/admin/cache/info",
			Handler:     deps.CacheHandler.Info,
			Op:          permission.AdminCacheInfo,
			Middlewares: baseMiddlewares,
			Tags:        "Admin - Cache",
			Summary:     "缓存信息",
			Description: "获取缓存信息",
		},
		{
			Method:      routes.GET,
			Path:        "/api/admin/cache/keys",
			Handler:     deps.CacheHandler.ScanKeys,
			Op:          permission.AdminCacheScanKeys,
			Middlewares: baseMiddlewares,
			Tags:        "Admin - Cache",
			Summary:     "扫描缓存键",
			Description: "扫描缓存键",
		},
		{
			Method:      routes.GET,
			Path:        "/api/admin/cache/key",
			Handler:     deps.CacheHandler.GetKey,
			Op:          permission.AdminCacheGetKey,
			Middlewares: baseMiddlewares,
			Tags:        "Admin - Cache",
			Summary:     "获取缓存键",
			Description: "获取缓存键值",
		},
		{
			Method:      routes.DELETE,
			Path:        "/api/admin/cache/key",
			Handler:     deps.CacheHandler.DeleteKey,
			Op:          permission.AdminCacheDeleteKey,
			Middlewares: auditMiddlewares,
			Tags:        "Admin - Cache",
			Summary:     "删除缓存键",
			Description: "删除缓存键",
		},
		{
			Method:      routes.DELETE,
			Path:        "/api/admin/cache/keys",
			Handler:     deps.CacheHandler.DeleteByPattern,
			Op:          permission.AdminCacheDeletePattern,
			Middlewares: auditMiddlewares,
			Tags:        "Admin - Cache",
			Summary:     "按模式删除缓存",
			Description: "按模式删除缓存",
		},
	}
}
