package http

import (
	"github.com/lwmacct/260101-go-pkg-ddd/pkg/adapters/http/routes"
)

// adminRoutes 返回 Admin 域所有路由
//
//nolint:maintidx // 路由定义是声明式配置，复杂度指标不适用
func (deps *RouterDependencies) adminRoutes() []routes.Route {
	// Admin 域中间件模式
	baseMiddlewares := []routes.MiddlewareConfig{
		{Name: routes.MiddlewareRequestID},
		{Name: routes.MiddlewareOperationID},
		{Name: routes.MiddlewareAuth},
		{Name: routes.MiddlewareRBAC},
	}
	auditMiddlewares := append(cloneMiddlewares(baseMiddlewares), routes.MiddlewareConfig{Name: routes.MiddlewareAudit})

	return []routes.Route{
		// ==================== 用户管理 ====================
		{
			Method:      routes.POST,
			Path:        "/api/admin/users",
			Handler:     deps.AdminUserHandler.CreateUser,
			Op:          "admin:users:create",
			Middlewares: auditMiddlewares,
			Tags:        "Admin - User Management",
			Summary:     "创建用户",
			Description: "创建新用户",
		},
		{
			Method:      routes.POST,
			Path:        "/api/admin/users/batch",
			Handler:     deps.AdminUserHandler.BatchCreateUsers,
			Op:          "admin:users:batch-create",
			Middlewares: auditMiddlewares,
			Tags:        "Admin - User Management",
			Summary:     "批量创建用户",
			Description: "批量创建用户",
		},
		{
			Method:      routes.GET,
			Path:        "/api/admin/users",
			Handler:     deps.AdminUserHandler.ListUsers,
			Op:          "admin:users:list",
			Middlewares: baseMiddlewares,
			Tags:        "Admin - User Management",
			Summary:     "用户列表",
			Description: "获取用户列表",
		},
		{
			Method:      routes.GET,
			Path:        "/api/admin/users/:id",
			Handler:     deps.AdminUserHandler.GetUser,
			Op:          "admin:users:get",
			Middlewares: baseMiddlewares,
			Tags:        "Admin - User Management",
			Summary:     "获取用户",
			Description: "获取用户详情",
		},
		{
			Method:      routes.PUT,
			Path:        "/api/admin/users/:id",
			Handler:     deps.AdminUserHandler.UpdateUser,
			Op:          "admin:users:update",
			Middlewares: auditMiddlewares,
			Tags:        "Admin - User Management",
			Summary:     "更新用户",
			Description: "更新用户信息",
		},
		{
			Method:      routes.DELETE,
			Path:        "/api/admin/users/:id",
			Handler:     deps.AdminUserHandler.DeleteUser,
			Op:          "admin:users:delete",
			Middlewares: auditMiddlewares,
			Tags:        "Admin - User Management",
			Summary:     "删除用户",
			Description: "删除用户",
		},
		{
			Method:      routes.PUT,
			Path:        "/api/admin/users/:id/roles",
			Handler:     deps.AdminUserHandler.AssignRoles,
			Op:          "admin:users:assign-roles",
			Middlewares: auditMiddlewares,
			Tags:        "Admin - User Management",
			Summary:     "分配角色",
			Description: "为用户分配角色",
		},

		// ==================== 角色管理 ====================
		{
			Method:      routes.POST,
			Path:        "/api/admin/roles",
			Handler:     deps.RoleHandler.CreateRole,
			Op:          "admin:roles:create",
			Middlewares: auditMiddlewares,
			Tags:        "Admin - Role Management",
			Summary:     "创建角色",
			Description: "创建角色",
		},
		{
			Method:      routes.GET,
			Path:        "/api/admin/roles",
			Handler:     deps.RoleHandler.ListRoles,
			Op:          "admin:roles:list",
			Middlewares: baseMiddlewares,
			Tags:        "Admin - Role Management",
			Summary:     "角色列表",
			Description: "获取角色列表",
		},
		{
			Method:      routes.GET,
			Path:        "/api/admin/roles/:id",
			Handler:     deps.RoleHandler.GetRole,
			Op:          "admin:roles:get",
			Middlewares: baseMiddlewares,
			Tags:        "Admin - Role Management",
			Summary:     "获取角色",
			Description: "获取角色详情",
		},
		{
			Method:      routes.PUT,
			Path:        "/api/admin/roles/:id",
			Handler:     deps.RoleHandler.UpdateRole,
			Op:          "admin:roles:update",
			Middlewares: auditMiddlewares,
			Tags:        "Admin - Role Management",
			Summary:     "更新角色",
			Description: "更新角色信息",
		},
		{
			Method:      routes.DELETE,
			Path:        "/api/admin/roles/:id",
			Handler:     deps.RoleHandler.DeleteRole,
			Op:          "admin:roles:delete",
			Middlewares: auditMiddlewares,
			Tags:        "Admin - Role Management",
			Summary:     "删除角色",
			Description: "删除角色",
		},
		{
			Method:      routes.PUT,
			Path:        "/api/admin/roles/:id/permissions",
			Handler:     deps.RoleHandler.SetPermissions,
			Op:          "admin:roles:set-permissions",
			Middlewares: auditMiddlewares,
			Tags:        "Admin - Role Management",
			Summary:     "设置权限",
			Description: "设置角色权限",
		},

		// ==================== 组织管理 ====================
		{
			Method:      routes.POST,
			Path:        "/api/admin/orgs",
			Handler:     deps.OrgHandler.Create,
			Op:          "admin:orgs:create",
			Middlewares: auditMiddlewares,
			Tags:        "Admin - Organizations",
			Summary:     "创建组织",
			Description: "创建组织",
		},
		{
			Method:      routes.GET,
			Path:        "/api/admin/orgs",
			Handler:     deps.OrgHandler.List,
			Op:          "admin:orgs:list",
			Middlewares: baseMiddlewares,
			Tags:        "Admin - Organizations",
			Summary:     "组织列表",
			Description: "获取组织列表",
		},
		{
			Method:      routes.GET,
			Path:        "/api/admin/orgs/:id",
			Handler:     deps.OrgHandler.Get,
			Op:          "admin:orgs:get",
			Middlewares: baseMiddlewares,
			Tags:        "Admin - Organizations",
			Summary:     "组织详情",
			Description: "获取组织详情",
		},
		{
			Method:      routes.PUT,
			Path:        "/api/admin/orgs/:id",
			Handler:     deps.OrgHandler.Update,
			Op:          "admin:orgs:update",
			Middlewares: auditMiddlewares,
			Tags:        "Admin - Organizations",
			Summary:     "更新组织",
			Description: "更新组织信息",
		},
		{
			Method:      routes.DELETE,
			Path:        "/api/admin/orgs/:id",
			Handler:     deps.OrgHandler.Delete,
			Op:          "admin:orgs:delete",
			Middlewares: auditMiddlewares,
			Tags:        "Admin - Organizations",
			Summary:     "删除组织",
			Description: "删除组织",
		},

		// ==================== 操作列表 ====================
		{
			Method:      routes.GET,
			Path:        "/api/admin/operations",
			Handler:     deps.OperationHandler.ListOperations,
			Op:          "admin:operations:list",
			Middlewares: baseMiddlewares,
			Tags:        "Admin - System",
			Summary:     "操作列表",
			Description: "获取所有操作",
		},

		// ==================== 审计日志 ====================
		{
			Method:      routes.GET,
			Path:        "/api/admin/audit/actions",
			Handler:     deps.AuditHandler.GetActions,
			Op:          "admin:audit:actions",
			Middlewares: baseMiddlewares,
			Tags:        "Admin - Audit",
			Summary:     "审计操作",
			Description: "获取审计操作列表",
		},
		{
			Method:      routes.GET,
			Path:        "/api/admin/audit",
			Handler:     deps.AuditHandler.ListLogs,
			Op:          "admin:audit:list",
			Middlewares: baseMiddlewares,
			Tags:        "Admin - Audit",
			Summary:     "审计日志",
			Description: "获取审计日志列表",
		},
		{
			Method:      routes.GET,
			Path:        "/api/admin/audit/:id",
			Handler:     deps.AuditHandler.GetLog,
			Op:          "admin:audit:get",
			Middlewares: baseMiddlewares,
			Tags:        "Admin - Audit",
			Summary:     "审计日志详情",
			Description: "获取审计日志详情",
		},

		// ==================== 系统概览 ====================
		{
			Method:      routes.GET,
			Path:        "/api/admin/overview/stats",
			Handler:     deps.OverviewHandler.GetStats,
			Op:          "admin:overview:stats",
			Middlewares: baseMiddlewares,
			Tags:        "Admin - Overview",
			Summary:     "系统概览",
			Description: "获取系统概览数据",
		},

		// ==================== 配置分类 ====================
		{
			Method:      routes.GET,
			Path:        "/api/admin/settings/categories",
			Handler:     deps.SettingHandler.GetCategories,
			Op:          "admin:setting:categories:list",
			Middlewares: baseMiddlewares,
			Tags:        "Admin - Settings",
			Summary:     "配置分类列表",
			Description: "获取配置分类列表",
		},
		{
			Method:      routes.GET,
			Path:        "/api/admin/settings/categories/:key",
			Handler:     deps.SettingHandler.GetCategory,
			Op:          "admin:setting:categories:get",
			Middlewares: baseMiddlewares,
			Tags:        "Admin - Settings",
			Summary:     "配置分类详情",
			Description: "获取配置分类详情",
		},
		{
			Method:      routes.POST,
			Path:        "/api/admin/settings/categories",
			Handler:     deps.SettingHandler.CreateCategory,
			Op:          "admin:setting:categories:create",
			Middlewares: auditMiddlewares,
			Tags:        "Admin - Settings",
			Summary:     "创建配置分类",
			Description: "创建配置分类",
		},
		{
			Method:      routes.PUT,
			Path:        "/api/admin/settings/categories/:key",
			Handler:     deps.SettingHandler.UpdateCategory,
			Op:          "admin:setting:categories:update",
			Middlewares: auditMiddlewares,
			Tags:        "Admin - Settings",
			Summary:     "更新配置分类",
			Description: "更新配置分类",
		},
		{
			Method:      routes.DELETE,
			Path:        "/api/admin/settings/categories/:key",
			Handler:     deps.SettingHandler.DeleteCategory,
			Op:          "admin:setting:categories:delete",
			Middlewares: auditMiddlewares,
			Tags:        "Admin - Settings",
			Summary:     "删除配置分类",
			Description: "删除配置分类",
		},

		// ==================== 系统配置 ====================
		{
			Method:      routes.POST,
			Path:        "/api/admin/settings/batch",
			Handler:     deps.SettingHandler.BatchUpdateSettings,
			Op:          "admin:settings:batch:update",
			Middlewares: auditMiddlewares,
			Tags:        "Admin - Settings",
			Summary:     "批量更新配置",
			Description: "批量更新系统配置",
		},
		{
			Method:      routes.POST,
			Path:        "/api/admin/settings",
			Handler:     deps.SettingHandler.CreateSetting,
			Op:          "admin:settings:create",
			Middlewares: auditMiddlewares,
			Tags:        "Admin - Settings",
			Summary:     "创建配置",
			Description: "创建系统配置",
		},
		{
			Method:      routes.GET,
			Path:        "/api/admin/settings",
			Handler:     deps.SettingHandler.GetSettings,
			Op:          "admin:settings:list",
			Middlewares: baseMiddlewares,
			Tags:        "Admin - Settings",
			Summary:     "配置列表",
			Description: "获取系统配置列表",
		},
		{
			Method:      routes.GET,
			Path:        "/api/admin/settings/:key",
			Handler:     deps.SettingHandler.GetSetting,
			Op:          "admin:settings:get",
			Middlewares: baseMiddlewares,
			Tags:        "Admin - Settings",
			Summary:     "配置详情",
			Description: "获取系统配置详情",
		},
		{
			Method:      routes.PUT,
			Path:        "/api/admin/settings/:key",
			Handler:     deps.SettingHandler.UpdateSetting,
			Op:          "admin:settings:update",
			Middlewares: auditMiddlewares,
			Tags:        "Admin - Settings",
			Summary:     "更新配置",
			Description: "更新系统配置",
		},
		{
			Method:      routes.DELETE,
			Path:        "/api/admin/settings/:key",
			Handler:     deps.SettingHandler.DeleteSetting,
			Op:          "admin:settings:delete",
			Middlewares: auditMiddlewares,
			Tags:        "Admin - Settings",
			Summary:     "删除配置",
			Description: "删除系统配置",
		},

		// ==================== 缓存管理 ====================
		{
			Method:      routes.GET,
			Path:        "/api/admin/cache/info",
			Handler:     deps.CacheHandler.Info,
			Op:          "admin:cache:info",
			Middlewares: baseMiddlewares,
			Tags:        "Admin - Cache",
			Summary:     "缓存信息",
			Description: "获取缓存信息",
		},
		{
			Method:      routes.GET,
			Path:        "/api/admin/cache/keys",
			Handler:     deps.CacheHandler.ScanKeys,
			Op:          "admin:cache:scan:keys",
			Middlewares: baseMiddlewares,
			Tags:        "Admin - Cache",
			Summary:     "扫描缓存键",
			Description: "扫描缓存键",
		},
		{
			Method:      routes.GET,
			Path:        "/api/admin/cache/key",
			Handler:     deps.CacheHandler.GetKey,
			Op:          "admin:cache:get:key",
			Middlewares: baseMiddlewares,
			Tags:        "Admin - Cache",
			Summary:     "获取缓存键",
			Description: "获取缓存键值",
		},
		{
			Method:      routes.DELETE,
			Path:        "/api/admin/cache/key",
			Handler:     deps.CacheHandler.DeleteKey,
			Op:          "admin:cache:delete:key",
			Middlewares: auditMiddlewares,
			Tags:        "Admin - Cache",
			Summary:     "删除缓存键",
			Description: "删除缓存键",
		},
		{
			Method:      routes.DELETE,
			Path:        "/api/admin/cache/keys",
			Handler:     deps.CacheHandler.DeleteByPattern,
			Op:          "admin:cache:delete:pattern",
			Middlewares: auditMiddlewares,
			Tags:        "Admin - Cache",
			Summary:     "按模式删除缓存",
			Description: "按模式删除缓存",
		},

		// ==================== 订单管理 ====================
		{
			Method:      routes.POST,
			Path:        "/api/admin/orders",
			Handler:     deps.OrderHandler.Create,
			Op:          "admin:orders:create",
			Middlewares: auditMiddlewares,
			Tags:        "Admin - Orders",
			Summary:     "创建订单",
			Description: "创建新订单",
		},
		{
			Method:      routes.GET,
			Path:        "/api/admin/orders",
			Handler:     deps.OrderHandler.List,
			Op:          "admin:orders:list",
			Middlewares: baseMiddlewares,
			Tags:        "Admin - Orders",
			Summary:     "订单列表",
			Description: "获取订单列表",
		},
		{
			Method:      routes.GET,
			Path:        "/api/admin/orders/:id",
			Handler:     deps.OrderHandler.Get,
			Op:          "admin:orders:get",
			Middlewares: baseMiddlewares,
			Tags:        "Admin - Orders",
			Summary:     "订单详情",
			Description: "获取订单详情",
		},
		{
			Method:      routes.PUT,
			Path:        "/api/admin/orders/:id",
			Handler:     deps.OrderHandler.Update,
			Op:          "admin:orders:update",
			Middlewares: auditMiddlewares,
			Tags:        "Admin - Orders",
			Summary:     "更新订单",
			Description: "更新订单信息",
		},
		{
			Method:      routes.PATCH,
			Path:        "/api/admin/orders/:id/status",
			Handler:     deps.OrderHandler.UpdateStatus,
			Op:          "admin:orders:update-status",
			Middlewares: auditMiddlewares,
			Tags:        "Admin - Orders",
			Summary:     "更新订单状态",
			Description: "更新订单状态",
		},
		{
			Method:      routes.DELETE,
			Path:        "/api/admin/orders/:id",
			Handler:     deps.OrderHandler.Delete,
			Op:          "admin:orders:delete",
			Middlewares: auditMiddlewares,
			Tags:        "Admin - Orders",
			Summary:     "删除订单",
			Description: "删除订单",
		},

		// ==================== 发票管理 ====================
		{
			Method:      routes.POST,
			Path:        "/api/admin/invoices",
			Handler:     deps.InvoiceHandler.Create,
			Op:          "admin:invoices:create",
			Middlewares: auditMiddlewares,
			Tags:        "Admin - Invoices",
			Summary:     "创建发票",
			Description: "创建新发票",
		},
		{
			Method:      routes.GET,
			Path:        "/api/admin/invoices",
			Handler:     deps.InvoiceHandler.List,
			Op:          "admin:invoices:list",
			Middlewares: baseMiddlewares,
			Tags:        "Admin - Invoices",
			Summary:     "发票列表",
			Description: "获取发票列表",
		},
		{
			Method:      routes.GET,
			Path:        "/api/admin/invoices/:id",
			Handler:     deps.InvoiceHandler.Get,
			Op:          "admin:invoices:get",
			Middlewares: baseMiddlewares,
			Tags:        "Admin - Invoices",
			Summary:     "发票详情",
			Description: "获取发票详情",
		},
		{
			Method:      routes.POST,
			Path:        "/api/admin/invoices/:id/pay",
			Handler:     deps.InvoiceHandler.Pay,
			Op:          "admin:invoices:pay",
			Middlewares: auditMiddlewares,
			Tags:        "Admin - Invoices",
			Summary:     "支付发票",
			Description: "支付发票（支持部分支付）",
		},
		{
			Method:      routes.POST,
			Path:        "/api/admin/invoices/:id/cancel",
			Handler:     deps.InvoiceHandler.Cancel,
			Op:          "admin:invoices:cancel",
			Middlewares: auditMiddlewares,
			Tags:        "Admin - Invoices",
			Summary:     "取消发票",
			Description: "取消发票",
		},
		{
			Method:      routes.POST,
			Path:        "/api/admin/invoices/:id/refund",
			Handler:     deps.InvoiceHandler.Refund,
			Op:          "admin:invoices:refund",
			Middlewares: auditMiddlewares,
			Tags:        "Admin - Invoices",
			Summary:     "退款",
			Description: "发票退款",
		},
	}
}
